[project]
name = "F-UEBA-Communication-Efficiency"
version = "1.2.0"

[data]
dataset_path = "./dataset/r4.2"
processed_data_path = "./ExtractedData/dayr4.2-percentile30.csv"
scaler_dir= "scaler_data"
scaler_filename_template = "scaler_client_{i}.pkl"
test_size = 0.2
batch_size = 128
is_non_iid = false
non_iid_alpha = 0.5
selected_features = [
    "isweekday", "isweekend", "n_workhourallact", "n_afterhourallact",
    "n_logon", "n_workhourlogon", "n_afterhourlogon", "logon_n-pc0", "logon_n-pc1", "logon_n-pc2",
    "n_usb", "usb_mean_usb_dur", "usb_n-pc0", "usb_n-pc1", "usb_n-pc2", "n_workhourusb", "n_afterhourusb",
    "n_file", "file_mean_file_len", "file_mean_file_depth", "file_mean_file_nwords", "file_n-disk0", "file_n-disk1",
    "file_n_otherf", "file_n_compf", "file_n_phof", "file_n_docf", "file_n_txtf", "file_n_exef",
    "n_email", "email_mean_n_des", "email_mean_n_atts", "email_n-Xemail1", "email_mean_n_exdes",
    "email_mean_n_bccdes", "email_n-exbccmail1", "email_mean_email_size", "email_mean_email_text_slen",
    "email_mean_email_text_nwords", "email_n-pc0", "email_n-pc1", "email_n-pc2",
    "n_http", "http_mean_url_len", "http_mean_url_depth", "http_mean_http_c_len", "http_mean_http_c_nwords",
    "http_n_socnetf", "http_n_cloudf", "http_n_jobf"
]

[federation]
num_rounds = 200
local_epochs = 5
fraction_fit = 0.5
min_fit_clients = 2
min_available_clients = 2
save_path = "./model_pickle"

[efficiency]
# You can now chain plugins! Order matters: top_k then quantization is usually best.
# example: active_plugins = ["top_k", "quantization"]
active_plugins = ["top_k", "quantization"]
top_k_ratio = 0.05

[model]
learning_rate = 0.0008
window_size = 14
stride = 1
hidden_dim = 128

[evaluation]
z_score_threshold = 7.5
metrics = ["precision", "recall", "f1", "auc_roc", "comm_overhead", "balanced_accuracy"]
